### ISSUE TITLE
Can't  install dplyr.spark.hive from source code

### ISSUE THREAD

**Issue by MarcinKosinski** [piccolbo/dplyr.spark.hive#10]
Hi! 

Opportunity of having a `dplyr` interface to the `hive` and `spark` sounds great.
I am trying to install `dplyr.spark.hive` package from source, strictly from the [newest release](https://github.com/piccolbo/dplyr.spark.hive/releases/tag/0.5.0)  but It looks like the `tar.gz` files is broken and the package can not be installed in this way. Could you kindly please provide a link to the non-broken `tar.gz` files? I've tried this procedure both on my ubuntu and CentOS and received such a warning:

``` R
> install.packages("~/dplyr.spark.hive-0.5.0.tar.gz", repos = NULL, type = "source")
Installing package into ‘/home/mkosinski/R/x86_64-pc-linux-gnu-library/3.2’
(as ‘lib’ is unspecified)
Warning in untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
ERROR: cannot extract package from ‘/home/mkosinski/dplyr.spark.hive-0.5.0.tar.gz’
Warning in install.packages :
  installation of package ‘/home/mkosinski/dplyr.spark.hive-0.5.0.tar.gz’ had non-zero exit status
```

**Comment by piccolbo** [comment]
That's not a package, it's just a tar file of everything. I can't fix it, it's a github thing. I could add other downloadables there, but you would still have to choose the right one. It's confusing, but I am not sure what to do about it. Can you go back to the README and follow the instructions therein? Thanks

**Comment by MarcinKosinski** [comment]
In the README there is an instruction to install package from your website.
This will not work on machines without internet connection or with blocked
PORTs.
That's why I am downloading source.
Ok so I will download everything, untar, and then I'll build source and
install a package.

2015-12-08 17:24 GMT+01:00 Antonio Piccolboni notifications@github.com:

**Comment by piccolbo** [comment]
I see your point. The direct url is http://r.piccolboni.info/src/contrib/dplyr.spark.hive_0.5.0.tar.gz
In my intuition this is not a common requirement, but I can re-evaluate that in the future.
