### ISSUE TITLE
Can't create dplyr src backed by SparkSQL in dplyr.spark.hive package

### ISSUE THREAD

**Issue by MarcinKosinski** [piccolbo/dplyr.spark.hive#11]
The problem is described in this [Stack Question](http://stackoverflow.com/questions/34267400/cant-create-dplyr-src-backed-by-sparksql-in-dplyr-spark-hive-package)

**Comment by piccolbo** [comment]
Answered there, hopefully

**Comment by MarcinKosinski** [comment]
Added 2 comments to your answer :) I think I'm close to the solution.

**Comment by MarcinKosinski** [comment]
Thanks for help @piccolbo! I am still having problem after I specified more path to global variables. Could you kindly please have a look at my edit2?

**Comment by piccolbo** [comment]
work going on in #15

**Comment by MarcinKosinski** [comment]
Ok this was the case of me not properly specifying `HADOOP_JAR` (or even not at all).  I think we can close this issue right now.

**Comment by piccolbo** [comment]
Thanks
